import type { Metadata } from 'next'
import { Black_Ops_One, Roboto_Flex} from 'next/font/google'
import './globals.css'

import ClientProvider from '../components/ClientProvider'

const fontLogo = Black_Ops_One({ 
  subsets: ['latin-ext'],
  weight: '400',
  variable: '--font-logo',
})

const fontBody = Roboto_Flex({
  subsets: ['latin'],
  variable: '--font-body',
})

export const metadata: Metadata = {
  title: 'Social Login with NextAuth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={`${fontBody.variable} ${fontLogo.variable} overflow-x-hidden font-body`}>
        <ClientProvider>
           {children}
        </ClientProvider>
      </body>
    </html>
    
  )
}
